### ISSUE TITLE
GoodSync checksum  miss mach 

### ISSUE THREAD

**Issue by apo-mak** [chtof/chocolatey-packages#19]
https://github.com/chtof/chocolatey-packages/tree/master/automatic/goodsync

> sha256sum  GoodSync-v10-Setup.msi
> b41a2bd54907092ff816d168391fde48fe039ae5c3ae6e644225c11f40ac758e  
GoodSync-v10-Setup.msi

but ps1 reports "d55369c59890640df23a9beebedd307a5dc681760387c3da0d34337b58e66a66"

here is the choco error 

> "ERROR: Checksum for 'C:\Users\Administrator\AppData\Local\Temp\chocolatey\GoodSync\11.1.6\GoodSync-v10-Setup.msi' did not meet 'd55369c59890640df23a9beebedd307a5dc681760387c3da0d34337b58e66a66' for checksum type 'sha256'."

**Comment by chtof** [comment]
Several versions have been submitted since version 11.1.6, 
Latest version is 11.3.5,  released 3 days ago and the checksum is the same.
I close this issue but you are welcome to open a new one of you have again a such issue.
For a major version (10, 11...), the URL for the binary is always the same... So, when they release a new version for the same major version, the checksum of the Chocolatey package can be incorrect until the Chocolatey is updated. It can takes about 3 and 12 hours to have a Chocolatey package updated with the new checksum.
